version: '3'

services:
  app:
    container_name: redcompc-app
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: chuongnh/gatsby-node:lts-alpine3.17
    env_file: .dev.env
    volumes:
      - ./:/app:delegated
      - /var/www/data/yarn/cache:/usr/local/share/.cache/yarn:delegated
      - /var/www/data/npm:/root/.npm:delegated
      - ./netlify-config.json:/home/root/.config/netlify/config.json:delegated
    working_dir: /app
    command: "yarn develop -- --port 8013 -H 0.0.0.0"
    # command: "yarn debug -- --port 8013 -H 0.0.0.0"
    # command: "yarn serve -- --port 9000 -H 0.0.0.0"
    ports:
      - "8013:8013"
      - "9000:9000"
      - "9929:9929"
      - "9230:9230"
  # cypress:
  #   # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
  #   image: "cypress/included:12.3.0"
  #   # depends_on:
  #   #   - sentimentalyzer
  #   # environment:
  #     # pass base url to test pointing at the web application
  #     # - CYPRESS_baseUrl=http://sentimentalyzer:8123
  #   # share the current folder as volume to avoid copying
  #   working_dir: /e2e
  #   volumes:
  #     - ./:/e2e