[build]
  command = "gatsby build"
  functions = "netlify/functions"
  publish = "public"
  environment = { NODE_VERSION = "18.13.0" }

[[plugins]]
  package = "@netlify/plugin-gatsby"


[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	# baseUrl = "https://pc.redcomgrp.com"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Time in seconds to not submit the sitemap after successful submission
	ignorePeriod = 0

	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]